---
title       : Data Visualization of mtcars DataSet
subtitle    : 
author      : godwinls
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Intro

THis is a visualization of two variables relationship in mtcars dataset

--- .class #id 

## Dataset

The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973-74 models).
```{r}
library(datasets)
head(mtcars, 5)
```

---

## Format

A data frame with 32 observations on 11 variables.

[, 1]         mpg	 Miles/(US) gallon

[, 2]	 cyl	 Number of cylinders

[, 3]	 disp	 Displacement (cu.in.)

[, 4]	 hp	 Gross horsepower

[, 5]	 drat	 Rear axle ratio

[, 6]	 wt	 Weight (lb/1000)

[, 7]	 qsec	 1/4 mile time

[, 8]	 vs	 V/S

[, 9]	 am	 Transmission (0 = automatic, 1 = manual)

[,10]	 gear	 Number of forward gears

[,11]	 carb	 Number of carburetors

---

## linear regression code

```{r}
regout <- reactive({
                lm(as.formula(paste(input$yaxis, " ~ ",paste(input$xaxis))), data = mtcars)
        })
```

